blog/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('', views.blog, name='blog'),
    path('<slug:slug>/', views.details, name='details'),
]

jobs/urls.py
from django.urls import path
from . import views

app_name = 'jobs'

urlpatterns = [
    path('', views.Home, name='home')
]

profiles/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'profiles'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('signup/', views.signup_user, name='signup_user'),
    path('login/', views.login_user, name='login_user'),
    path('edit_profile', views.edit_profile, name='edit_profile'),
    path('password_update', views.password_update, name='password_update'),
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='password_reset.html',
                                                                email_template_name='password_reset_email.html',
                                                                subject_template_name='password_reset_subject.txt',
                                                                success_url='/dashboard/password_reset/done/'),
         name='password_reset'),
    path('password_reset_confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html', success_url='/dashboard/password_reset/complete/'),
         name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
         name='password_reset_complete'),
    path('logout/', views.logout_user, name='logout_user'),
]

second/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from profiles import views


urlpatterns = [
    path('', include('jobs.urls')),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('dashboard/', include('profiles.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify


class Article(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    image = models.ImageField(upload_to='images/')
    created_At = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def summary(self):
        return self.content[:50] + "..."

    def pretty_date(self):
        return self.created_At.strftime('%b %m %Y')

    def save(self, *args, **kwargs):
            # Newly created object, so set slug
        self.slug = slugify(self.title)
        super(Article, self).save(*args, **kwargs)

profiles/models.py
from django.db import models

profiles/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms


class EditProfileForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', )


class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email", widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username',
                  'email', 'password1', 'password2',)

    # def __init__(self, *args, **kwargs):
    #     super(SignUpForm, self).__init__(*args, **kwargs)

        # self.fields['first_name'].widget.attrs['class'] = 'form-control'
    #     self.fields['first_name'].widget.attrs['placeholder'] = 'First Name'
    #     self.fields['first_name'].label = ""
        # self.fields['last_name'].widget.attrs['class'] = 'form-control'
    #     self.fields['last_name'].widget.attrs['placeholder'] = 'Last Name'
    #     self.fields['last_name'].label = ""
        # self.fields['username'].widget.attrs['class'] = 'form-control'
    # self.fields['username'].widget.attrs['placeholder'] = 'Username'
    #     self.fields['username'].label = ""
    #     self.fields['username'].help_text = '<div class="form-group"><small class="form-text text-muted">Required. less than 15 words.. excluding @/./+/-</small></div>'
        # self.fields['password1'].widget.attrs['class'] = 'form-control'
    #     self.fields['password1'].widget.attrs['placeholder'] = 'Password'
    #     self.fields['password1'].label = ""
    #     self.fields['password1'].help_text = '<div class="form-group"><small class="form-text text-muted"><ul><li>Your password can\'t be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can\'t be a commonly used password.</li><li>Your password can\'t be entirely numeric.</li></ul></small></div >'
        # self.fields['password2'].widget.attrs['class'] = 'form-control'
    #     self.fields['password2'].widget.attrs['placeholder'] = 'Confirm Password'
    #     self.fields['password2'].label = ""
    #     self.fields['password2'].help_text = '<div class="form-group"><small class="form-text text-muted">Enter the same password as before, for verification.</small></div>'

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Article


def blog(request):
    if request.user.is_authenticated:
        articles = Article.objects.all()
        context = {'articles': articles}
        return render(request, 'blog.html', context)

    return render(request, 'blog.html',)


def details(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'single_post.html', {'article': article})

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.views import PasswordChangeForm, PasswordResetForm, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetConfirmView
from django.contrib import messages
from .forms import SignUpForm, EditProfileForm


def dashboard(request):
    if request.user.is_authenticated:
        return render(request, 'profile.html')
    else:
        messages.success(request, 'You are not logged in... Please login..')
        return redirect('profiles:login_user')


def signup_user(request):
    if request.user.is_authenticated:
        return redirect('profiles:dashboard')

    else:
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data['username']
                password = form.cleaned_data['password1']
                user = authenticate(username=username, password=password)
                login(request, user)
                messages.success(
                    request, 'You have been successfully registered...')
                return redirect('profiles:dashboard')

        else:
            form = SignUpForm()

        context = {'form': form}
        return render(request, 'register.html', context)


def login_user(request):
    if request.user.is_authenticated:
        return redirect('blogs:blog')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, 'Successfully logged In')
                return redirect('blogs:blog')

            else:
                messages.success(
                    request, 'Login failed - Please Try again....')
                return redirect('profiles:login_user')

        else:
            return render(request, 'login.html')


def edit_profile(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = EditProfileForm(request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                messages.success(
                    request, 'Profile successfully updated...')
                return redirect('profiles:dashboard')

        else:
            form = EditProfileForm(instance=request.user)

        context = {'form': form}
        return render(request, 'edit_profile.html', context)


def password_update(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PasswordChangeForm(data=request.POST, user=request.user)
            if form.is_valid():
                form.save()
                update_session_auth_hash(request, form.user)
                messages.success(
                    request, 'Password successfully updated...')
                return redirect('profiles:dashboard')

        else:
            form = PasswordChangeForm(user=request.user)

        context = {'form': form}
        return render(request, 'password_update.html', context)


def logout_user(request):
    logout(request)
    messages.success(request, 'You have been successfully logged out!!!..')
    return redirect('blogs:blog')

templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="https://getbootstrap.com/favicon.ico">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'album.css' %}" rel="stylesheet">
</head>

<body>

    <header>
        <div class="collapse bg-dark" id="navbarHeader">
            <div class="container">
                <div class="row">
                    <div class="col-sm-8 col-md-7 py-4">
                        <h4 class="text-white">About</h4>
                        <p class="text-muted">Add some information about the album below, the author, or any other
                            background
                            context. Make it a few sentences long so folks can pick up some informative tidbits. Then,
                            link them off
                            to some social networking sites or contact information.</p>
                    </div>
                    <div class="col-sm-4 offset-md-1 py-4">
                        <h4 class="text-white">Contact</h4>
                        <ul class="list-unstyled">
                            <li><a href="{% url 'jobs:home' %}" class="text-white">Follow on Twitter</a></li>
                            <li><a href="{% url 'jobs:home' %}" class="text-white">Like on Facebook</a></li>
                            <li><a href="{% url 'jobs:home' %}" class="text-white">Email me</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container d-flex justify-content-between">
                <a href="{% url 'jobs:home' %}" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                        <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                        <circle cx="12" cy="13" r="4"></circle>
                    </svg>
                    <strong>Portfolio</strong>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'blogs:blog' %}">Blog</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" data-toggle="collapse" aria-expanded="false" aria-controls="navbarHeader"
                                data-target="#navbarHeader" style="cursor: pointer;">About</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <div class="dropdown nav-link" style="cursor: default;">
                                {{ user.username }}
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="nav-link" href="{% url 'profiles:dashboard' %}">Profile</a>
                                    <a class="nav-link" href="{% url 'profiles:logout_user' %}">Logout</a>
                                </div>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'profiles:login_user' %}">Login</a>
                        </li>
                        {% endif %}

                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main">
        {% if messages %}
        {% for message in messages %}
        <div class="container">
            <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 20px;">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        {% endfor %}
        {% endif %}

        {% block content %}
        {% endblock %}
    </main>

    <footer class="text-muted fixed-bottom">

        <div class="text-center">
            <p>
                Copyright All Rights Reserved {% now "Y" %}
            </p>
        </div>

    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'popper.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <script src="{% static 'holder.min.js' %}"></script>


    <svg xmlns="http://www.w3.org/2000/svg" width="348" height="225" viewBox="0 0 348 225" preserveAspectRatio="none"
        style="display: none; visibility: hidden; position: absolute; top: -100%; left: -100%;">
        <defs>
            <style type="text/css"></style>
        </defs><text x="0" y="17" style="font-weight:bold;font-size:17pt;font-family:Arial, Helvetica, Open Sans, sans-serif">Thumbnail</text>
    </svg>
</body>

</html>

templates/edit_profile.html
{% extends 'base_layout.html' %}
{% block content %}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Profile</div>
                <div class="card-body">
                    <form name="my-form" action="{% url 'profiles:edit_profile' %}" method="POST">
                        {% csrf_token %}

                        {% include 'form.html' %}
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Save
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock%}

templates/form.html
{% load form_tags widget_tweaks %}

{% if form.errors %}
<div class="container">
    <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 20px;">
        {% for field in form %}
        {% if field.errors %}
        {{ field.errors }}
        {% endif %}
        {% endfor %}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
</div>

{% endif %}


{% for field in form %}
<div class="form-group row">
    <label class="col-md-4 col-form-label text-md-right"> {{ field.label_tag }}</label>
    <div class="col-md-6">
        {% render_field field class=field|input_class %}
        {% if field.help_text %}
        <small class="form-text text-muted">
            {{ field.help_text|safe }}
        </small>
        {% endif %}
    </div>

</div>
{% endfor %}

templates/home.html
{% extends 'base_layout.html' %}
{% block title %} Home {% endblock %}

{% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Hi, I am Manish. A begginner in django.</h1>
    <p class="lead text-muted">Well, i am still figuring out what to write here so this can be used as dummy text</p>
    <p>
      <a href="" class="btn btn-primary my-2">Email Me</a>
    </p>
  </div>
</section>

<div class="album py-5 bg-light">
  <div class="container">

    <div class="row">

      {% for job in jobs.all %}

      <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
          <img class="card-img-top" data-src="holder.js/100px225?theme=thumb&amp;bg=55595c&amp;fg=eceeef&amp;text=Thumbnail"
            alt="Thumbnail [100%x225]" style="height: 225px; width: 100%; display: block;" src="{{ job.image.url }}" />
          <div class="card-body">
            <p class="card-text">{{ job.summary }}</p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
              </div>
              <small class="text-muted">9 mins</small>
            </div>
          </div>
        </div>
      </div>

      {% endfor %}
    </div>
  </div>
</div>

{% endblock%}

templates/login.html
{% extends 'base_layout.html' %}
{% block title %} Login {% endblock %}
{% block content %}
<br>
<br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">
                    <form name="my-form" action="{% url 'profiles:login_user' %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label for="username" class="col-md-4 col-form-label text-md-right">Username</label>
                            <div class="col-md-6">
                                <input type="text" id="username" class="form-control" name="username">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="password" class="col-md-4 col-form-label text-md-right">Password</label>
                            <div class="col-md-6">
                                <input type="password" id="password" class="form-control" name="password">
                            </div>
                        </div>

                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Login
                            </button>
                        </div>
                </div>
                </form>
                <div class="card-footer text-muted text-center">
                    Don't have an account? <a href="{% url 'profiles:signup_user' %}">Register</a>
                </div>
            </div>
            <div class="text-center py-2">
                <small>
                    <a href="{% url 'profiles:password_reset' %}" class="text-muted">Forgot your password?</a>
                </small>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/password_reset.html
{% extends 'base_layout.html' %}

{% block title %}Reset your password {% endblock %}

{% block content %}
<br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">
                    <h3 class="card-title">Reset your password</h3>
                    <p>Enter your email address and we will send you a link to reset your password.</p>
                    <form action="{% url 'profiles:password_reset' %}" method="POST" novalidate>
                        {% csrf_token %}
                        {% include 'form.html' %}
                        <div class="col-md-6 offset-md-5">
                            <button type="submit" class="btn btn-primary">
                                Send
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_complete.html
{% extends 'base_layout.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
<br>

<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Password Reset Completed</h3>
                <p>Congrats!!! Your password has been successfully changes...</p>
                <a href="{% url 'profiles:login_user' %}" class="btn btn-secondary btn-block">Return to log in</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_confirm.html
{% extends 'base_layout.html' %}

{% block title %}
{% if validlink %}
Change password for {{ form.user.username }}
{% else %}
Reset your password
{% endif %}
{% endblock %}

{% block content %}
<br>

<div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <div class="card">
            <div class="card-body">
                {% if validlink %}
                <h3 class="card-title">Change password for @{{ form.user.username }}</h3>
                <form method="POST" action="" novalidate>
                    {% csrf_token %}
                    {% include 'form.html' %}
                    <button type="submit" class="btn btn-success btn-block">Change password</button>
                </form>
                {% else %}
                <h3 class="card-title">Reset your password</h3>
                <div class="alert alert-danger" role="alert">
                    It looks like you clicked on an invalid password reset link. Please try again.
                </div>
                <a href="{% url 'profiles:password_reset' %}" class="btn btn-secondary btn-block">Request a new
                    password reset
                    link</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_layout.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
<br>

<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Reset your password</h3>
                <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check
                    your spam folder.</p>
                <a href="{% url 'profiles:login_user' %}" class="btn btn-secondary btn-block">Return to log in</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}. Follow the link below:
{{ protocol }}://{{ domain }}{% url 'profiles:password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Maharudra username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL in a new browser window instead.

If you've received this mail in error, it's likely that another user entered your email address by mistake while trying
to reset a password. If you didn't initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Maharudra Team

templates/password_update.html
{% extends 'base_layout.html' %}
{% block content %}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Profile</div>
                <div class="card-body">
                    <form name="my-form" action="{% url 'profiles:password_update' %}" method="POST">
                        {% csrf_token %}

                        {% if form.errors %}
                        <div class="container">
                            <div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-top: 20px;">
                                {% for field in form %}
                                {% if field.errors %}
                                {{ field.errors }}
                                {% endif %}
                                {% endfor %}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        </div>

                        {% endif %}

                        {{ form.as_p }}


                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Save
                            </button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock%}

templates/register.html
{% extends 'base_layout.html' %}
{% block title %} Signup {% endblock %}

{% block content %}
<br>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">
                    <form name="my-form" action="{% url 'profiles:signup_user' %}" method="POST">
                        {% csrf_token %}
                        {% include 'form.html' %}
                        <div class="col-md-6 offset-md-5">
                            <button type="submit" class="btn btn-primary">
                                Register
                            </button>
                        </div>

                    </form>

                </div>
                <div class="card-footer text-muted text-center">
                    Already have an account? <a href="{% url 'profiles:login_user' %}">Log in</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock%}

templates/signup.html
{% extends 'base_layout.html' %}
{% block content %}
<br>
<br>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Register</div>
                <div class="card-body">
                    <form name="my-form" action="{% url 'profiles:signup_user' %}" method="">
                        <div class="form-group row">
                            <label for="full_name" class="col-md-4 col-form-label text-md-right">Name</label>
                            <div class="col-md-6">
                                <input type="text" id="full_name" class="form-control" name="full-name">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="email_address" class="col-md-4 col-form-label text-md-right">Username</label>
                            <div class="col-md-6">
                                <input type="text" id="email_address" class="form-control" name="email-address">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="user_name" class="col-md-4 col-form-label text-md-right">Email</label>
                            <div class="col-md-6">
                                <input type="text" id="user_name" class="form-control" name="username">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="phone_number" class="col-md-4 col-form-label text-md-right">Password</label>
                            <div class="col-md-6">
                                <input type="text" id="phone_number" class="form-control">
                            </div>
                        </div>

                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                Register
                            </button>
                        </div>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock%}

templates/single_post.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="container">
    <div class="article-details">
        <div class="article">
            <br>
            <h2>{{ article.title }}</h2>
            <h6>{{ article.pretty_date }}</h6>
            <br>
            <img src="{{ article.image.url }}" alt="" class="image-fluid" height="400px" width="1140px">
            <p>{{ article.content }}</p>
        </div>
    </div>
</div>
{% endblock%}